core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import homePage


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', homePage, name="home"),

    path('user/', include('user.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from .views import (registerUser,
                    registerVendor,
                    otpRegisterValidation,
                    loginUser,
                    logoutUser,
                    myAccount,
                    custDashboard,
                    vendorDashboard,
                    forgetPasswordEmail,
                    resetLinkEmail,
                    confirmResettingEmail,
                    )


app_name = "user"

urlpatterns = [
    path('register/', registerUser, name='register'),
    path('registerVendor/', registerVendor, name='registerVendor'),
    
    path('otp/', otpRegisterValidation, name='otpValidation'),

    path('', loginUser, name='login'),
    path('logout/', logoutUser, name='logout'),

    path('myAccount/', myAccount, name='myAccount'),

    path('custDashboard/', custDashboard, name='custDashboard'),
    path('vendorDashboard/', vendorDashboard, name='vendorDashboard'),

    path('forget-password-email/', forgetPasswordEmail, name='forget-password-email'),
    path('reset-link-email/<uidb64>/<token>/', resetLinkEmail, name='reset-link-email'),
    path('confirm-reset-email/', confirmResettingEmail, name='confirm-reset-email'),
]

templates/root.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <title>{% block title %} {% endblock title %}</title>
    <meta content="" name="description" />
    <meta content="" name="keywords" />

    <!-- Favicons -->
    <link href="{% static 'img/favicon.png' %}" rel="icon" />
    <link
      href="{% static 'img/apple-touch-icon.png' %}"
      rel="apple-touch-icon"
    />

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect" />
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Amatic+SC:wght@400;700&display=swap"
      rel="stylesheet"
    />

    <!-- Vendor CSS Files -->
    <link
      href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}"
      rel="stylesheet"
    />
    <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet" />
    <link
      href="{% static 'vendor/glightbox/css/glightbox.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'vendor/swiper/swiper-bundle.min.css' %}"
      rel="stylesheet"
    />

    <!-- Main CSS File -->
    <link href="{% static 'css/main.css' %}" rel="stylesheet" />

    <!--  =======================================================
  * Template Name: Yummy
  * Template URL: https://bootstrapmade.com/yummy-bootstrap-restaurant-website-template/
  * Updated: Jun 29 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ========================================================  -->
  </head>

  <body class="index-page">
    <header id="header" class="header d-flex align-items-center sticky-top">
      <div
        class="container position-relative d-flex align-items-center justify-content-between"
      >
        <a
          href="{% url 'home' %}"
          class="logo d-flex align-items-center me-auto me-xl-0"
        >
          <!-- Uncomment the line below if you also wish to use an image logo -->
          <!-- <img src="assets/img/logo.png" alt=""> -->
          <h1 class="sitename">Yummy</h1>
          <span>.</span>
        </a>

        <nav id="navmenu" class="navmenu">
          <ul>
            <li>
              <a href="{% url 'home' %}" class="active">Home<br /></a>
            </li>
            <li>
              <a href="#">About</a>
            </li>
            <li>
              <a href="#">Menu</a>
            </li>
            <li>
              <a href="#">Events</a>
            </li>
            <li>
              <a href="#">Chefs</a>
            </li>
            <li>
              <a href="#">Gallery</a>
            </li>
            {% comment %}
            <li class="dropdown">
              <a href="#"
                ><span>Dropdown</span>
                <i class="bi bi-chevron-down toggle-dropdown"></i
              ></a>
              <ul>
                <li>
                  <a href="#">Dropdown 1</a>
                </li>
                <li class="dropdown">
                  <a href="#"
                    ><span>Deep Dropdown</span>
                    <i class="bi bi-chevron-down toggle-dropdown"></i
                  ></a>
                  <ul>
                    <li>
                      <a href="#">Deep Dropdown 1</a>
                    </li>
                    <li>
                      <a href="#">Deep Dropdown 2</a>
                    </li>
                    <li>
                      <a href="#">Deep Dropdown 3</a>
                    </li>
                    <li>
                      <a href="#">Deep Dropdown 4</a>
                    </li>
                    <li>
                      <a href="#">Deep Dropdown 5</a>
                    </li>
                  </ul>
                </li>
                <li>
                  <a href="#">Dropdown 2</a>
                </li>
                <li>
                  <a href="#">Dropdown 3</a>
                </li>
                <li>
                  <a href="#">Dropdown 4</a>
                </li>
              </ul>
            </li>
            {% endcomment %}
            <li>
              <a href="#">Contact</a>
            </li>
          </ul>
          <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
        </nav>

        
        {% if request.user.is_authenticated %}
        <a class="btn-getstarted" href="{% url 'user:myAccount' %}">
          Dashboard
        </a>
        <a class="btn-getstarted" href="{% url 'user:logout' %}">
          Logout
        </a>
        {% else %}
        <a class="btn-getstarted" href="{% url 'user:login' %}"
          >Login/Register</a
        >
          
        {% endif %}
          
        <a class="btn-getstarted" href="{% url 'user:registerVendor' %}"
          >Register Vendor</a
        >
      </div>
    </header>

    <main class="main">{% block doc %} {% endblock %}</main>

    <footer id="footer" class="footer dark-background">
      <div class="container">
        <div class="row gy-3">
          <div class="col-lg-3 col-md-6 d-flex">
            <i class="bi bi-geo-alt icon"></i>
            <div class="address">
              <h4>Address</h4>
              <p>A108 Adam Street</p>
              <p>New York, NY 535022</p>
              <p></p>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 d-flex">
            <i class="bi bi-telephone icon"></i>
            <div>
              <h4>Contact</h4>
              <p>
                <strong>Phone:</strong> <span>+1 5589 55488 55</span><br />
                <strong>Email:</strong> <span>info@example.com</span><br />
              </p>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 d-flex">
            <i class="bi bi-clock icon"></i>
            <div>
              <h4>Opening Hours</h4>
              <p>
                <strong>Mon-Sat:</strong> <span>11AM - 23PM</span><br />
                <strong>Sunday</strong>: <span>Closed</span>
              </p>
            </div>
          </div>

          <div class="col-lg-3 col-md-6">
            <h4>Follow Us</h4>
            <div class="social-links d-flex">
              <a href="#" class="twitter"><i class="bi bi-twitter-x"></i></a>
              <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
              <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
              <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
            </div>
          </div>
        </div>
      </div>

      <div class="container copyright text-center mt-4">
        <p>
          © <span>Copyright</span> <strong class="px-1 sitename">Yummy</strong>
          <span>All Rights Reserved</span>
        </p>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you've purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
    </footer>

    <!-- Scroll Top -->
    <a
      href="#"
      id="scroll-top"
      class="scroll-top d-flex align-items-center justify-content-center"
      ><i class="bi bi-arrow-up-short"></i
    ></a>

    <!-- Preloader -->
    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'vendor/aos/aos.js' %}"></script>
    <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>

    <!-- Main JS File -->
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>